package com.dicoding.jetcharacters.model

object CharactersDataSource {
    val characters = listOf(
        Character(
            "1",
            "Alhaitham",
            "The current scribe of the Sumeru Akademiya, a man endowed with extraordinary intelligence and talent. He lives free — free from the searching eyes of ordinary people, anyway.",
            "https://static.wikia.nocookie.net/gensin-impact/images/2/2c/Alhaitham_Icon.png",
            "https://genshindb.org/wp-content/uploads/2023/01/Alhaitham-Splash-Art.webp",
            "Dendro",
            "Vultur Volans",
        ),
        Character(
            "2",
            "Ayato",
            "The young but highly accomplished head of the Yashiro Commission\\'s Kamisato Clan. Cultured and polite, he is a man of many ways and means.",
            "https://static.wikia.nocookie.net/gensin-impact/images/2/27/Kamisato_Ayato_Icon.png",
            "https://genshindb.org/wp-content/uploads/2022/03/Kamisato-Ayato-Splash-Art.png",
            "Hydro",
            "Cypressus Custos",
        ),
        Character(
            "3",
            "Childe",
            "No. 11 of The Harbingers, also known as \"Childe.\" His name is highly feared on the battlefield.",
            "https://static.wikia.nocookie.net/gensin-impact/images/8/85/Tartaglia_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/01/Tartaglia-Splash-Art.png",
            "Hydro",
            "Monoceros Caeli",
        ),
        Character(
            "4",
            "Eula",
            "The Spindrift Knight, a scion of the old aristocracy, and the Captain of the Knights of Favonius Reconnaissance Company.",
            "https://static.wikia.nocookie.net/gensin-impact/images/a/af/Eula_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/03/Eula-Splash-Art.png",
            "Cryo",
            "Aphros Delos",
        ),
        Character(
            "5",
            "Kaeya",
            "An accomplished swordsman and a strategic thinker in the Knights of Favonius, rumored to hail from beyond Mondstadt.",
            "https://static.wikia.nocookie.net/gensin-impact/images/b/b6/Kaeya_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/01/Kaeya-Splash-Art.png",
            "Cryo",
            "Pavo Ocellus",
        ),
        Character(
            "6",
            "Kazuha",
            "A wandering samurai from Inazuma who is currently with Liyues Crux Fleet. A gentle and carefree soul whose heart hides a great many burdens from the past.",
            "https://static.wikia.nocookie.net/gensin-impact/images/e/e3/Kaedehara_Kazuha_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/04/Kaedehara-Kazuha-Splash-Art.png",
            "Anemo",
            "Acer Palmatum",
        ),
        Character(
            "7",
            "Kokomi",
            "The Divine Priestess of Watatsumi Island. All of the island\\'s affairs are at this young lady\\'s fingertips.",
            "https://static.wikia.nocookie.net/gensin-impact/images/f/ff/Sangonomiya_Kokomi_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/07/Sangonomiya-Kokomi-Splash-Art.png",
            "Hydro",
            "Dracaena Somnolenta",
        ),
        Character(
            "8",
            "Raiden",
            "Her Excellency, the Almighty Narukami Ogosho, who promised the people of Inazuma an unchanging Eternity.",
            "https://static.wikia.nocookie.net/gensin-impact/images/2/24/Raiden_Shogun_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/07/Raiden-Shogun-Splash-Art.png",
            "Electro",
            "Imperatrix Umbrosa",
        ),
        Character(
            "9",
            "Yoimiya",
            "Owner of Naganohara Fireworks. Known as Queen of the Summer Festival, she excels in her craft of creating fireworks that symbolize people\\'s hopes and dreams.",
            "https://static.wikia.nocookie.net/gensin-impact/images/8/88/Yoimiya_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/06/Yoimiya-Splash-Art.png",
            "Pyro",
            "Carassius Auratus",
        ),
        Character(
            "10",
            "Zhongli",
            "A mysterious expert contracted by the Wangsheng Funeral Parlor. Extremely knowledgeable in all things.",
            "https://static.wikia.nocookie.net/gensin-impact/images/a/a6/Zhongli_Icon.png",
            "https://genshindb.org/wp-content/uploads/2021/01/Zhongli-Splash-Art.png",
            "Geo",
            "Lapis Dei",
        )
    )
}
